package gp9_nutricionista.vistas;

import nutricionista_persistencia.PacienteData;
import gp9_nutricionista.modelo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author agust
 */
public class PacienteVista extends javax.swing.JInternalFrame {

    private PacienteData pacd = new PacienteData();
    private boolean activo = false;

    public PacienteVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTEdad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBEliminar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jTEstado = new javax.swing.JRadioButton();
        jTNombre = new javax.swing.JTextField();
        jBLimpiar = new javax.swing.JButton();
        jBModificar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTAltura = new javax.swing.JTextField();
        jTPesoA = new javax.swing.JTextField();
        jTPesoD = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PACIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 130, 25));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("id:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Edad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jTId.setBackground(new java.awt.Color(204, 204, 204));
        jTId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTIdKeyTyped(evt);
            }
        });
        jPanel1.add(jTId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jTEdad.setBackground(new java.awt.Color(204, 204, 204));
        jTEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTEdadKeyTyped(evt);
            }
        });
        jPanel1.add(jTEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 150, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Estado:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Altura:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 87, -1));

        jBGuardar.setText("Crear");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 87, -1));

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jTEstado.setBackground(new java.awt.Color(204, 204, 204));
        jTEstado.setForeground(new java.awt.Color(0, 51, 51));
        jTEstado.setText("Activo");
        jTEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTEstado.setBorderPainted(true);
        jTEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(jTEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jTNombre.setBackground(new java.awt.Color(204, 204, 204));
        jTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreKeyTyped(evt);
            }
        });
        jPanel1.add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, -1));

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 87, -1));

        jBModificar1.setText("Modificar");
        jBModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 87, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Peso Actual:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Peso Deseado:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jTAltura.setBackground(new java.awt.Color(204, 204, 204));
        jTAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTAlturaKeyTyped(evt);
            }
        });
        jPanel1.add(jTAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 140, -1));

        jTPesoA.setBackground(new java.awt.Color(204, 204, 204));
        jTPesoA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTPesoAKeyTyped(evt);
            }
        });
        jPanel1.add(jTPesoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 140, -1));

        jTPesoD.setBackground(new java.awt.Color(204, 204, 204));
        jTPesoD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTPesoDKeyTyped(evt);
            }
        });
        jPanel1.add(jTPesoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIdKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {

            evt.consume();
        }
    }//GEN-LAST:event_jTIdKeyTyped

    private void jTEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTEdadKeyTyped
     char validar = evt.getKeyChar();
     if(Character.isLetter(validar)){
     evt.consume();
     
     }
    }//GEN-LAST:event_jTEdadKeyTyped

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        
        if(!jTId.getText().isEmpty()){
        int id = Integer.parseInt(jTId.getText());
        
        pacd.borrarPaciente(id);
        }
        limpiarFormulario();
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        
        try{
        Paciente p = new Paciente();
        
        String nombre = jTNombre.getText();
        int e = Integer.parseInt(jTEdad.getText());
        float a = Float.parseFloat(jTAltura.getText());
        float pa = Float.parseFloat(jTPesoA.getText());
        float pd = Float.parseFloat(jTPesoD.getText());
        boolean bo = jTEstado.isSelected();
       
        p.setNombre(nombre);
        p.setEdad(e);
        p.setAltura(a);
        p.setPesoActual(pa);
        p.setPesoBuscado(pd);
        p.setEstado(bo);
        
        if (!jTId.getText().isEmpty()) {
                int cod = Integer.parseInt(jTId.getText());
                p.setNroPaciente(cod);
               pacd.agregarPacienteId(p);
        }else{pacd.agregarPaciente(p); }
        
       
        limpiarFormulario();
    }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Datos no validos");
    
    }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
       try{
         int id = Integer.parseInt(jTId.getText());
        Paciente p = new Paciente();
         p = pacd.buscarPaciente(id);
        
        jTNombre.setText(p.getNombre());
        jTEdad.setText(p.getEdad()+"");
        jTEstado.setSelected(p.isEstado());
        jTAltura.setText(p.getAltura()+"");
        jTPesoA.setText(p.getPesoActual()+"");
        jTPesoD.setText(p.getPesoBuscado()+"");
        
        
       
        
    }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Debe ingresar un id para poder buscar al paciente");
      limpiarFormulario();
    }

    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEstadoActionPerformed
        activo=true;

    }//GEN-LAST:event_jTEstadoActionPerformed

    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyTyped
    char validar = evt.getKeyChar();
    if(Character.isDigit(validar)){
    evt.consume();
    
    
    }
    
    
    }//GEN-LAST:event_jTNombreKeyTyped

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificar1ActionPerformed
        
        if(!jTId.getText().isEmpty()){
        Paciente p = new Paciente();
        int id = Integer.parseInt(jTId.getText());
        String nombre = jTNombre.getText();
        int e = Integer.parseInt(jTEdad.getText());
        float a = Float.parseFloat(jTAltura.getText());
        float pa = Float.parseFloat(jTPesoA.getText());
        float pd = Float.parseFloat(jTPesoD.getText());
        boolean bo = jTEstado.isSelected();
       
        p.setNroPaciente(id);
        p.setNombre(nombre);
        p.setEdad(e);
        p.setAltura(a);
        p.setPesoActual(pa);
        p.setPesoBuscado(pd);
        p.setEstado(bo);
        
        pacd.modificarPaciente(p);
        }else{
        JOptionPane.showMessageDialog(null, "Debe ingresar el id");}
        
        
        
       
    }//GEN-LAST:event_jBModificar1ActionPerformed

    private void jTAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAlturaKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
        evt.consume();
        
        
        }
    }//GEN-LAST:event_jTAlturaKeyTyped

    private void jTPesoAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPesoAKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
        evt.consume();
        
        }
    }//GEN-LAST:event_jTPesoAKeyTyped

    private void jTPesoDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPesoDKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
        evt.consume();
        
        }
    }//GEN-LAST:event_jTPesoDKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTAltura;
    private javax.swing.JTextField jTEdad;
    private javax.swing.JRadioButton jTEstado;
    private javax.swing.JTextField jTId;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPesoA;
    private javax.swing.JTextField jTPesoD;
    // End of variables declaration//GEN-END:variables

    public void limpiarFormulario() {
        jTId.setText("");
        jTNombre.setText("");
        jTAltura.setText("");
        jTEdad.setText("");
        jTPesoA.setText("");
        jTPesoD.setText("");
        jTEstado.setSelected(false);
        jTEstado.setEnabled(true);
    }
}
